### PR TITLE
Ouakhila

### PR DESCRIPTION
**Pull request by Ouakhila**
I am working on the On click button, there are some code to add. work in progress

### CODE REVIEW

**Comment by suzi01** [comment]
Hi Ouakhila,

It looks good so far!  Just a couple of things:

- the onclick function is not working. You need to reference the imported array, **dates**,  in the innterHTML such as ${dates.image} instead of ${image}. 

- Also, the code for the image should be:

descriptive image

instead of:

descriptive image

as the array image attribute in the array already contains ""

- Lastly, you need to create a div with the class **modal-container** to contain all the information as right now it's trying to put all the information in the Read More button. 

Also, because I changed a little bit of my code to resolve an issue with one of the automated tests,  there are some conflicts on your branch but we will sort those out either tomorrow or Saturday so don't worry about it. 

Let me know if you need any help! :)

**Review by Ouakhila — COMMENTED** [review]
Hello Suzi please checkout the code

**Comment by Ouakhila** [comment]
The for loop i have implemented does not increment. I think something is wrong with the for loop.

**Review by suzi01 — APPROVED** [review]
Hi Ouakhila, 

Glad to know the video helped. I have made changes to resolve the merging confilcts but you're code will be added so no issues. The last thing will be to have the specific classes on the modal but that won't be a big issue. Really  happy you managed to create the modal! :D

**Pull request merged**
